base_model: Qwen/Qwen3-4B
hub_model_id: minpeter/LoRA-Qwen3-4b-v1-iteration-02-sf-apigen-02

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: minpeter/apigen-mt-5k-friendli
    data_files:
      - train.jsonl
      - test.jsonl
    type: chat_template
    roles_to_train: ["assistant"]
    field_messages: messages
    message_property_mappings:
      role: role
      content: content
chat_template: chatml

dataset_prepared_path: last_run_prepared

output_dir: ./output

adapter: qlora
lora_model_dir:

sequence_len: 20000
pad_to_sequence_len: true
sample_packing: true

val_set_size: 0.05
eval_sample_packing: true
evals_per_epoch: 3

lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

wandb_project: "axolotl"
wandb_entity: "kasfiekfs-e"
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 2
num_epochs: 2
optimizer: adamw_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_steps: 10
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
